today = None
g_month_chosen_stock_list = []
g_chosen_stock_list = []
buy_stock_count = 4
sellrank = buy_stock_count * 2
score = 6
begin_money = 200000
stock_info = {'value': 100, 'stock_number': 100, 'value_per': 1}
portfolio = {'positions': {}, 'total_value': begin_money, 'free_money': begin_money, 'stock_value': 0}
daily_df = None
trade_date = None
trade_date_time = None
cal_date = None
account_num = '20200106'
path = 'D:/dbzjtest/userdata_mini'
total_value = begin_money
acc = None
xt_trader = None
